title: Md Ashiqur Rahman
description: Software Engineer,NybSys
baseurl: "/about/"
url: ""
photo_url: "my-photo.jpg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "ashiq.mail.net@gmail.com"
linkedin: "http://linkedin.com/in/ashiqs"
github: "https://github.com/ashiqqs"
website: "http://ashiqqs.github.io/"
medium: "https://tahanima.medium.com/"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
